<?php
include_once('../../../global.php');


class App extends App_Admin_Ajax
{
    private $wid;
    private $month;
    private $fixedInput;
    private $staffSalary;
    private $otherInput;
    private $offlineLogisticsFee;
    private $id;

    protected function checkAuth()
    {
        parent::checkAuth('hc_edit_warehouse_fee'); // TODO: Change the autogenerated stub
    }

    protected function getPara()
    {
        $this->id = Tool_Input::clean('r', 'id', TYPE_UINT);
        $this->wid = Tool_Input::clean('r', 'wid', TYPE_UINT);
        $this->month = Tool_Input::clean('r', 'month', TYPE_STR);
        $this->fixedInput = Tool_Input::clean('r', 'fixed_input', TYPE_NUM);
        $this->staffSalary = Tool_Input::clean('r', 'staff_salary', TYPE_NUM);
        $this->otherInput = Tool_Input::clean('r', 'other_input', TYPE_NUM);
        $this->offlineLogisticsFee = Tool_Input::clean('r', 'offline_logistics_fee', TYPE_NUM);
    }

    protected function checkPara()
    {
        if ($this->wid <= 0)
        {
            throw new Exception('请选择仓库！');
        }
        if (empty($this->month))
        {
            throw new Exception('请填写月份！');
        }

        $this->fixedInput *= 100;
        $this->staffSalary *= 100;
        $this->otherInput *= 100;
        $this->offlineLogisticsFee *= 100;
    }

    protected function main()
    {
        if (empty($this->id))
        {
            Statistics_Api::addWarehouseFee($this->wid, $this->month, $this->fixedInput, $this->staffSalary, $this->otherInput, $this->offlineLogisticsFee, $this->_uid);
        }
        else
        {
            Statistics_Api::updateWarehouseFee($this->id, $this->wid, $this->month, $this->fixedInput, $this->staffSalary, $this->otherInput, $this->offlineLogisticsFee, $this->_uid);
        }
    }

    protected function outputPage()
    {
        $result = array('succ' => true);
        $response = new Response_Ajax();
        $response->setContent($result);
        $response->send();

        exit;
    }
}

$app = new App('pri');
$app->run();
