insert into server_setting(master_sid,host,port,user,passwd,active,remark) values
(0,'127.0.0.1',3306,'root','',1,'');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_customer', 1, 't_customer', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_user', 1, 't_user', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_coupon', 1, 't_coupon', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_coupon_apply', 1, 't_coupon_apply', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_cashback', 1, 't_cashback', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_sms_queue', 1, 't_sms_queue', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_customer_history', 1, 't_customer_history', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_construction_site', 1, 't_construction_site', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_community', 1, 't_community', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_order', 1, 't_order', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_order_product', 1, 't_order_product', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_order_line', 1, 't_order_line', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_driver_queue', 1, 't_driver_queue', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_order_history', 1, 't_order_history', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_brand', 1, 't_brand', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_cate_brand', 1, 't_cate_brand', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_model', 1, 't_model', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_sku', 1, 't_sku', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_product', 1, 't_product', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_sku_2_location', 1, 't_sku_2_location', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_sku_location_history', 1, 't_sku_location_history', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_in_order', 1, 't_in_order', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_in_order_product', 1, 't_in_order_product', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_stock_in', 1, 't_stock_in', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_stock_in_product', 1, 't_stock_in_product', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_stock_in_refund', 1, 't_stock_in_refund', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_stock_shift', 1, 't_stock_shift', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_stock_shift_product', 1, 't_stock_shift_product', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_refund', 1, 't_refund', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_money_out_history', 1, 't_money_out_history', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_money_in_history', 1, 't_money_in_history', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_customer_amount_history', 1, 't_customer_amount_history', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_coopworker_money_out_history', 1, 't_coopworker_money_out_history', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_coopworker_order', 1, 't_coopworker_order', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_coopworker_statement', 1, 't_coopworker_statement', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_stock', 1, 't_stock', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_stock_history', 1, 't_stock_history', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_supplier', 1, 't_supplier', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_picture', 1, 't_picture', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_staff_user', 1, 't_staff_user', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_sku_fulltext', 1, 't_sku_fulltext', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_statistics_order', 1, 't_statistics_order', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_customer_tracking', 1, 't_customer_tracking', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_weixin_customer', 1, 't_weixin_customer', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_weixin_info', 1, 't_weixin_info', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_kvstore', 1, 't_kvstore', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_driver', 1, 't_driver', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_carrier', 1, 't_carrier', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_admin_log', 1, 't_admin_log', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_admin_log_2017', 1, 't_admin_log_2017', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_business', 1, 't_business', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_temporary_purchase', 1, 't_temporary_purchase', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_temporary_had_purchased', 1, 't_temporary_had_purchased', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_customer_limit', 1, 't_customer_limit', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_collect_mobile', 1, 't_collect_mobile', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_order_statistics', 1, 't_order_statistics', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_order_privilege', 1, 't_order_privilege', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_order_action_log', 1, 't_order_action_log', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_admin_task', 1, 't_admin_task', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_admin_task_history', 1, 't_admin_task_history', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_cumulative_log', 1, 't_cumulative_log', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_user_channel', 1, 't_user_channel', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_lottery_record', 1, 't_lottery_record', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_user_weixin_location', 1, 't_user_weixin_location', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_third_party_sku_mapping', 1, 't_third_party_sku_mapping', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_community_distance_fee', 1, 't_community_distance_fee', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_manjian_activity', 1, 't_manjian_activity', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_invite_customer', 1, 't_invite_customer', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_invite_reward', 1, 't_invite_reward', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_after_sale', 1, 't_after_sale', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_after_sale_log', 1, 't_after_sale_log', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_logistics_action_log', 1, 't_logistics_action_log', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_activity_picture', 1, 't_activity_picture', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_weixin_coopworker', 1, 't_weixin_coopworker', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_user_regid', 1, 't_user_regid', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_hot_search', 1, 't_hot_search', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_flash_sale', 1, 't_flash_sale', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_flash_sale_activity', 1, 't_flash_sale_activity', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_floor_activity', 1, 't_floor_activity', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_floor_sale', 1, 't_floor_sale', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_article', 1, 't_article', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_user_fb', 1, 't_user_fb', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_user_msg', 1, 't_user_msg', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_quick_order', 1, 't_quick_order', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_user_kvstore', 1, 't_user_kvstore', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_user_often_buy', 1, 't_user_often_buy', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_statistics_receivables', 1, 't_statistics_receivables', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_shortcut', 1, 't_shortcut', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_hotword', 1, 't_hotword', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_service_feature', 1, 't_service_feature', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_promotion_manjian_activity', 1, 't_promotion_manjian_activity', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_promotion_coupon', 1, 't_promotion_coupon', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_driver_location', 1, 't_driver_location', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_app_version', 1, 't_app_version', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_message', 1, 't_message', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_role', 1, 't_role', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_exchanged', 1, 't_exchanged', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_inventory_plan', 1, 't_inventory_plan', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_inventory_task', 1, 't_inventory_task', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_inventory_products', 1, 't_inventory_products', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_traps', 1, 't_traps', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_weixin_limit', 1, 't_weixin_limit', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_weixin_record', 1, 't_weixin_record', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_statistics_base_per_day', 1, 't_statistics_base_per_day', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_statistics_base_per_month', 1, 't_statistics_base_per_month', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_statistics_buyer_per_month', 1, 't_statistics_buyer_per_month', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_statistics_sku_per_day', 1, 't_statistics_sku_per_day', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_statistics_cate_sku_per_day', 1, 't_statistics_cate_sku_per_day', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_statistics_brand_sku_per_day', 1, 't_statistics_brand_sku_per_day', 'id', 1, '');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_statistics_warehouse_cost', 1, 't_statistics_warehouse_cost', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_customer', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_user', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_coupon', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_coupon_apply', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_cashback', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_sms_queue', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_customer_history', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_construction_site', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_community', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_order', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_order_product', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_order_line', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_driver_queue', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_order_history', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_brand', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_cate_brand', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_model', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_sku', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_product', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_sku_2_location', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_sku_location_history', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_in_order', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_in_order_product', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_stock_in', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_stock_in_product', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_stock_in_refund', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_stock_shift', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_stock_shift_product', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_refund', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_money_out_history', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_money_in_history', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_customer_amount_history', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_coopworker_money_out_history', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_coopworker_order', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_coopworker_statement', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_stock', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_stock_history', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_supplier', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_picture', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_staff_user', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_sku_fulltext', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_statistics_order', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_customer_tracking', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_weixin_customer', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_weixin_info', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_kvstore', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_driver', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_carrier', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_admin_log', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_admin_log_2017', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_business', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_temporary_purchase', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_temporary_had_purchased', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_customer_limit', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_collect_mobile', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_order_statistics', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_order_privilege', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_order_action_log', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_admin_task', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_admin_task_history', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_cumulative_log', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_user_channel', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_lottery_record', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_user_weixin_location', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_third_party_sku_mapping', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_community_distance_fee', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_manjian_activity', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_invite_customer', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_invite_reward', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_after_sale', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_after_sale_log', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_logistics_action_log', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_activity_picture', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_weixin_coopworker', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_user_regid', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_hot_search', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_flash_sale', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_flash_sale_activity', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_floor_activity', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_floor_sale', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_article', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_user_fb', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_user_msg', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_quick_order', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_user_kvstore', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_user_often_buy', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_statistics_receivables', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_shortcut', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_hotword', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_service_feature', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_promotion_manjian_activity', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_promotion_coupon', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_driver_location', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_app_version', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_message', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_role', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_exchanged', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_inventory_plan', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_inventory_task', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_inventory_products', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_traps', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_weixin_limit', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_weixin_record', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_statistics_base_per_day', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_statistics_base_per_month', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_statistics_buyer_per_month', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_statistics_sku_per_day', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_statistics_cate_sku_per_day', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_statistics_brand_sku_per_day', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_statistics_warehouse_cost', 0, 1, 'haocai_test');


insert into table_setting(kind,no,sid,db_name) values ('t_order_comment', 0, 1, 'haocai_test');
insert into table_setting(kind,no,sid,db_name) values ('t_order_cancel_reason', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_sale_schedule', 1, 't_sale_schedule', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_sale_schedule', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_customer_visit', 1, 't_customer_visit', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_customer_visit', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_customer_relative', 1, 't_customer_relative', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_customer_relative', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_cart', 1, 't_cart', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_cart', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_cpoint_product', 1, 't_cpoint_product', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_cpoint_product', 0, 1, 'haocai_test');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_cpoint_history', 1, 't_cpoint_history', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_cpoint_history', 0, 1, 'haocai_test');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_cpoint_stock_history', 1, 't_cpoint_stock_history', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_cpoint_stock_history', 0, 1, 'haocai_test');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_cpoint_order', 1, 't_cpoint_order', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_cpoint_order', 0, 1, 'haocai_test');
insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_cpoint_order_product', 1, 't_cpoint_order_product', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_cpoint_order_product', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_toc_case', 1, 't_toc_case', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_toc_case', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_toc_wiki', 1, 't_toc_wiki', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_toc_wiki', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_toc_appointment', 1, 't_toc_appointment', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_toc_appointment', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_toc_forman', 1, 't_toc_forman', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_toc_forman', 0, 1, 'haocai_test');

insert into kind_setting(kind, table_num, table_prefix, id_field, version, remark) values('t_out_trade', 1, 't_out_trade', 'id', 1, '');
insert into table_setting(kind,no,sid,db_name) values ('t_out_trade', 0, 1, 'haocai_test');